import{A as L,S as y,N as b,K as h,a as E,d as I,b as _}from"./assets/vendor-b2236c86.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))m(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&m(l)}).observe(document,{childList:!0,subtree:!0});function i(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerPolicy&&(r.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?r.credentials="include":n.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function m(n){if(n.ep)return;n.ep=!0;const r=i(n);fetch(n.href,r)}})();const q=document.getElementById("hero-contacts"),B=document.createElement("ul"),T=[{name:"IG",url:"https://www.instagram.com/goitclub/"},{name:"FB",url:"https://www.facebook.com/goITclub/"},{name:"YT",url:"https://www.youtube.com/c/GoIT"},{name:"GH",url:"https://github.com/Arhangels1/project-14"}],A=T.map(e=>`<li><a href='${e.url}' target='_blank'>${e.name}</a></li>`).join("");B.insertAdjacentHTML("beforeend",A);q.appendChild(B);const S=document.createElement("p"),u=document.createElement("a");u.href="mailto:lloydjefferson@gmail.com";u.textContent="lloydjefferson@gmail.com";S.appendChild(u);q.appendChild(S);new L(".about-me__list");new y(".projects-swiper",{modules:[b,h],navigation:{nextEl:".projects-button-next",prevEl:".projects-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0}});new L(".faq-all-questions");document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".faq-item").forEach(t=>{t.querySelector(".faq-question").addEventListener("click",()=>{t.classList.toggle("active");const i=t.querySelector(".faq-answer");t.classList.contains("active")?i.style.display="block":i.style.display="none"})})});const V={modules:[b,h],navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},direction:"horizontal",keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},767:{slidesPerView:2,spaceBetween:16},1439:{slidesPerView:4,spaceBetween:16}}},k=new y(".swiper-reviews",V);k.on("reachBeginning",function(){o.prevBtn.classList.add("reviews-prev-btn-off"),o.nextBtn.classList.remove("reviews-prev-btn-off")});k.on("reachEnd",function(){o.nextBtn.classList.add("reviews-prev-btn-off"),o.prevBtn.classList.remove("reviews-prev-btn-off")});const o={slideWrapper:document.querySelector(".reviews-swiper-wrapper"),prevBtn:document.querySelector(".reviews-prev-btn"),nextBtn:document.querySelector(".reviews-next-btn")};o.prevBtn.classList.add("reviews-prev-btn-off");async function O(){const e=await E.get("https://portfolio-js.b.goit.study/api/reviews",{headers:{accept:"application/json"}});o.slideWrapper.insertAdjacentHTML("afterbegin",P(e.data))}O();function $(e){return`<div class="swiper-slide reviews-swiper-slide">
          <img
            class="reviews-img"
            src="${e.avatar_url}"
            alt="Natalia"
          />
          <div class="reviews-desc">
            <p class="reviews-name">${e.author}</p>
            <p class="reviews-text">${e.review}</p>
          </div>
        </div>`}function P(e){return e.map($).join("")}o.nextBtn.addEventListener("click",()=>{o.prevBtn.classList.remove("reviews-prev-btn-off")});o.prevBtn.addEventListener("click",()=>{o.nextBtn.classList.remove("reviews-prev-btn-off")});document.addEventListener("keydown",e=>{e.preventDefault(),e.code==="ArrowRight"&&o.prevBtn.classList.remove("reviews-prev-btn-off"),e.code==="ArrowLeft"&&o.nextBtn.classList.remove("reviews-prev-btn-off")});const H="https://portfolio-js.b.goit.study/api";async function N(e){try{return await E.post(`${H}/requests`,e)}catch(t){return t}}const x=document.querySelector(".footer__form"),c=document.querySelector('input[name="comment"]'),p=document.querySelector('input[name="email"]'),s=document.querySelector(".footer__form--is-valid"),v=document.querySelector(".loader"),j=document.querySelector(".backdrop"),a=document.querySelector(".modal"),w=33;let f="";p.addEventListener("input",I(R,300));c.addEventListener("input",F);c.addEventListener("blur",G);c.addEventListener("focus",K);x.addEventListener("submit",W);j.addEventListener("click",Y);function R(e){z(e),D()}function D(){p.value.length<=0&&(s.textContent="")}function F(e){f=e.target.value}function G(e){e.target.value.length>w&&(e.target.value=e.target.value.substring(0,w)+"...")}function K(e){e.target.value=f}function W(e){e.preventDefault();const t=new FormData(x);v.classList.remove("is-hidden"),N(Object.fromEntries(t)).then(i=>{v.classList.add("is-hidden"),a.innerHTML=g(i.data),d(),_.on(),window.addEventListener("keydown",M)}).catch(i=>{a.innerHTML=g({title:"Error"}),d()}),U()}function M(e){e.code==="Escape"&&C()}function z(e){e.target.checkValidity()?(s.classList.add("footer__form--valid"),s.classList.remove("footer__form--invalid"),s.textContent="Success"):(s.classList.remove("footer__form--valid"),s.classList.add("footer__form--invalid"),s.textContent="Invalid email, try again")}function d(){j.classList.toggle("is-hidden--modal"),a.classList.toggle("animate__bounceInRight"),a.classList.toggle("backdrop__modal__animation")}function U(){p.value="",c.value="",s.textContent="",f=""}function Y(e){e.currentTarget===e.target&&C()}function C(){d(),_.off(),window.removeEventListener("keydown",M)}function g({title:e,message:t}){return`<div class="backdrop__modal__content">
        <h4>${e}</h4>
        ${t?`<p>${t}</p>`:""}
      </div>`}
//# sourceMappingURL=commonHelpers.js.map
