import{S as g,N as y,K as L,a as b,d as k,b as h,A as E}from"./assets/vendor-9de38571.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))p(n);new MutationObserver(n=>{for(const o of n)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&p(l)}).observe(document,{childList:!0,subtree:!0});function i(n){const o={};return n.integrity&&(o.integrity=n.integrity),n.referrerPolicy&&(o.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?o.credentials="include":n.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function p(n){if(n.ep)return;n.ep=!0;const o=i(n);fetch(n.href,o)}})();const V={modules:[y,L],navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},direction:"horizontal",keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},767:{slidesPerView:2,spaceBetween:16},1439:{slidesPerView:4,spaceBetween:16}}},_=new g(".swiper-reviews",V);_.on("reachBeginning",function(){r.prevBtn.classList.add("reviews-prev-btn-off"),r.nextBtn.classList.remove("reviews-prev-btn-off")});_.on("reachEnd",function(){r.nextBtn.classList.add("reviews-prev-btn-off"),r.prevBtn.classList.remove("reviews-prev-btn-off")});const r={slideWrapper:document.querySelector(".reviews-swiper-wrapper"),prevBtn:document.querySelector(".reviews-prev-btn"),nextBtn:document.querySelector(".reviews-next-btn")};r.prevBtn.classList.add("reviews-prev-btn-off");async function j(){const e=await b.get("https://portfolio-js.b.goit.study/api/reviews",{headers:{accept:"application/json"}});r.slideWrapper.insertAdjacentHTML("afterbegin",A(e.data))}j();function O(e){return`<div class="swiper-slide reviews-swiper-slide">
          <img
            class="reviews-img"
            src="${e.avatar_url}"
            alt="Natalia"
          />
          <div class="reviews-desc">
            <p class="reviews-name">${e.author}</p>
            <p class="reviews-text">${e.review}</p>
          </div>
        </div>`}function A(e){return e.map(O).join("")}r.nextBtn.addEventListener("click",()=>{r.prevBtn.classList.remove("reviews-prev-btn-off")});r.prevBtn.addEventListener("click",()=>{r.nextBtn.classList.remove("reviews-prev-btn-off")});document.addEventListener("keydown",e=>{e.preventDefault(),e.code==="ArrowRight"&&r.prevBtn.classList.remove("reviews-prev-btn-off"),e.code==="ArrowLeft"&&r.nextBtn.classList.remove("reviews-prev-btn-off")});const I="https://portfolio-js.b.goit.study/api";async function M(e){try{return await b.post(`${I}/requests`,e)}catch(t){return t}}const q=document.querySelector(".footer__form"),c=document.querySelector('input[name="comment"]'),u=document.querySelector('input[name="email"]'),s=document.querySelector(".footer__form--is-valid"),v=document.querySelector(".loader"),S=document.querySelector(".backdrop"),a=document.querySelector(".modal"),m=33;let f="";u.addEventListener("input",k(C,300));c.addEventListener("input",$);c.addEventListener("blur",N);c.addEventListener("focus",R);q.addEventListener("submit",T);S.addEventListener("click",H);function C(e){D(e),P()}function P(){u.value.length<=0&&(s.textContent="")}function $(e){f=e.target.value}function N(e){e.target.value.length>m&&(e.target.value=e.target.value.substring(0,m)+"...")}function R(e){e.target.value=f}function T(e){e.preventDefault();const t=new FormData(q);v.classList.remove("is-hidden"),M(Object.fromEntries(t)).then(i=>{v.classList.add("is-hidden"),a.innerHTML=w(i.data),d(),h.on(),window.addEventListener("keydown",B)}).catch(i=>{a.innerHTML=w({title:"Error"}),d()}),F()}function B(e){e.code==="Escape"&&x()}function D(e){e.target.checkValidity()?(s.classList.add("footer__form--valid"),s.classList.remove("footer__form--invalid"),s.textContent="Success"):(s.classList.remove("footer__form--valid"),s.classList.add("footer__form--invalid"),s.textContent="Invalid email, try again")}function d(){S.classList.toggle("is-hidden--modal"),a.classList.toggle("animate__bounceInRight"),a.classList.toggle("backdrop__modal__animation")}function F(){u.value="",c.value="",s.textContent="",f=""}function H(e){e.currentTarget===e.target&&x()}function x(){d(),h.off(),window.removeEventListener("keydown",B)}function w({title:e,message:t}){return`<div class="backdrop__modal__content">
        <h4>${e}</h4>
        ${t?`<p>${t}</p>`:""}
      </div>`}new g(".projects-swiper",{modules:[y,L],navigation:{nextEl:".projects-button-next",prevEl:".projects-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0}});new E(".faq-all-questions");document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".faq-item").forEach(t=>{t.querySelector(".faq-question").addEventListener("click",()=>{t.classList.toggle("active");const i=t.querySelector(".faq-answer");t.classList.contains("active")?i.style.display="block":i.style.display="none"})})});new E(".about-me__list");
//# sourceMappingURL=commonHelpers.js.map
